version: 0.0
os: linux

files:
  - source: /app3/
    destination: /var/www/app3

file_exists_behavior: OVERWRITE

permissions:
  - object: /app3/app3
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
